#!/bin/bash

# Example as below
#Install two-factor-autheticacion module
#modman clone https://github.com/magento-hackathon/Magento-Two-factor-Authentication.git
#Copy option, this i want
#modman deploy --copy Magento-Two-factor-Authentication

